import { useState, useEffect } from 'react'
import { Button, message, Tooltip, Input } from 'antd'
import { InfoCircleOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { confirmTotpKeyReq } from '../../requests'
import { useMerchantMemberProfileStore } from '../../stores'

const TwoFactorVerify = () => {
  const [verificationCode, setVerificationCode] = useState([
    '',
    '',
    '',
    '',
    '',
    ''
  ])
  const [loading, setLoading] = useState(false)
  const navigate = useNavigate()
  const merchantMemberProfile = useMerchantMemberProfileStore()

  useEffect(() => {
    const profile = merchantMemberProfile.getProfile()
    if (profile.totpType && profile.totpType > 0) {
      message.info('You have already set up two-factor authentication')
      navigate('/plan/list')
      return
    }
  }, [navigate, merchantMemberProfile])

  const handleInputChange = (index: number, value: string) => {
    if (value.length <= 1 && /^\d*$/.test(value)) {
      const newCode = [...verificationCode]
      newCode[index] = value
      setVerificationCode(newCode)

      if (value && index < 5) {
        const nextInput = document.getElementById(`code-${index + 1}`)
        nextInput?.focus()
      }
    }
  }

  const handlePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault()
    const pastedData = e.clipboardData.getData('text').replace(/\D/g, '').slice(0, 6)
    if (pastedData.length > 0) {
      const newCode = [...verificationCode]
      for (let i = 0; i < 6; i++) {
        newCode[i] = pastedData[i] || ''
      }
      setVerificationCode(newCode)
      const focusIndex = Math.min(pastedData.length, 5)
      const targetInput = document.getElementById(`code-${focusIndex}`)
      targetInput?.focus()
    }
  }

  const handleKeyDown = (
    index: number,
    e: React.KeyboardEvent<HTMLInputElement>
  ) => {
    if (e.key === 'Backspace' && !verificationCode[index] && index > 0) {
      const prevInput = document.getElementById(`code-${index - 1}`)
      prevInput?.focus()
    }
  }

  const handleVerify = async () => {
    const code = verificationCode.join('')
    if (code.length !== 6) {
      message.error('Please enter a complete 6-digit code')
      return
    }

    const totpKey = sessionStorage.getItem('totpKey')
    const totpTypeStr = sessionStorage.getItem('totpType')

    if (!totpKey) {
      message.error('TOTP key not found. Please go back and try again.')
      return
    }

    const totpType = totpTypeStr ? parseInt(totpTypeStr, 10) : 1

    setLoading(true)
    try {
      const [, err] = await confirmTotpKeyReq(totpType, totpKey, code)
      if (err) {
        message.error('Verification failed. Please try again.')
        return
      }

      message.success('Two-factor authentication setup successful!')

      merchantMemberProfile.setProfile({
        ...merchantMemberProfile.getProfile(),
        totpType: totpType
      })

      sessionStorage.removeItem('totpKey')
      sessionStorage.removeItem('totpType')

      navigate('/plan/list')
    } catch {
      message.error('Failed to verify code. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div
      style={{
        width: '100%',
        maxWidth: '1320px',
        margin: '0 auto',
        padding: '0 16px',
        marginTop: '60px'
      }}
    >
      <div style={{ marginBottom: '32px', marginTop: '30px' }}>
        <h1
          style={{
            fontWeight: 600,
            marginBottom: '16px',
            textAlign: 'center',
            fontSize: '28px'
          }}
        >
          Set Up Two-Factor Authentication (2FA)
          <Tooltip title="Two-factor authentication adds an extra layer of security to your account. When logging in, you'll need to enter a verification code generated by your authenticator app in addition to your password.">
            <InfoCircleOutlined
              style={{
                marginLeft: '8px',
                fontSize: '20px',
                verticalAlign: 'middle'
              }}
            />
          </Tooltip>
        </h1>
      </div>

      <div
        style={{
          padding: '24px',
          backgroundColor: 'white',
          borderRadius: '8px',
          marginTop: '20px',
          minHeight: '660px'
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            marginBottom: '32px'
          }}
        >
          <span style={{ fontSize: '18px', fontWeight: 500 }}>Verify Setup</span>
        </div>

        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            width: '100%',
            maxWidth: '443px',
            margin: '0 auto',
            marginTop: '64px'
          }}
        >
          <div style={{ textAlign: 'center', marginBottom: '32px' }}>
            <p style={{ color: '#6B7280' }}>
              Check the current 6-digit verification code and enter it below:
            </p>
          </div>

          <div style={{ marginBottom: '32px', width: '100%' }}>
            <div
              style={{ textAlign: 'center', marginBottom: '16px', marginTop: '34px' }}
            >
              <label
                style={{ fontSize: '14px', fontWeight: 500, color: '#374151' }}
              >
                Verification Code
              </label>
            </div>
            <div
              style={{
                display: 'flex',
                justifyContent: 'center',
                gap: '8px'
              }}
            >
              {verificationCode.map((digit, index) => (
                <Input
                  key={index}
                  id={`code-${index}`}
                  maxLength={1}
                  value={digit}
                  onChange={(e) => handleInputChange(index, e.target.value)}
                  onKeyDown={(e) =>
                    handleKeyDown(index, e as React.KeyboardEvent<HTMLInputElement>)
                  }
                  onPaste={handlePaste}
                  style={{
                    width: '64px',
                    height: '74px',
                    textAlign: 'center',
                    fontSize: '24px',
                    fontWeight: 500
                  }}
                  disabled={loading}
                />
              ))}
            </div>
          </div>

          <div style={{ width: '100%' }}>
            <Button
              type="primary"
              size="large"
              style={{
                width: '100%',
                height: '50px',
                marginTop: '70px'
              }}
              onClick={handleVerify}
              disabled={loading || verificationCode.join('').length !== 6}
              loading={loading}
            >
              {loading ? 'Verifying...' : 'Verify'}
            </Button>
          </div>
        </div>
      </div>

      <div
        style={{
          position: 'sticky',
          bottom: 0,
          display: 'flex',
          justifyContent: 'flex-start',
          marginTop: '24px',
          paddingBottom: '16px',
          borderTop: '1px solid #E5E7EB',
          paddingTop: '16px',
          backgroundColor: '#f5f5f5'
        }}
      >
        <Button
          size="large"
          onClick={() => navigate(-1)}
          disabled={loading}
        >
          Back
        </Button>
      </div>
    </div>
  )
}

export default TwoFactorVerify
