import { useEffect, useState } from 'react'
import { Button, message, Tooltip, Alert, Spin } from 'antd'
import { CopyOutlined, InfoCircleOutlined, CheckCircleOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import TwoFactorQRCode from './TwoFactorQRCode'
import { getTotpKeyReq, GetTotpKeyData } from '../../requests'
import { useMerchantMemberProfileStore } from '../../stores'

const authenticatorOptions = [
  { value: 1, label: 'Google Authenticator' },
  { value: 2, label: 'Microsoft Authenticator' },
  { value: 3, label: 'Authy' },
  { value: 4, label: '1Password' },
  { value: 5, label: 'LastPass' },
  { value: 6, label: 'FreeOTP' },
  { value: 7, label: 'Other TOTP App' }
]

const SESSION_STORAGE_KEY_PREVIOUS_TOTP_RESUME_CODE =
  'twoFactorSetup_previousTotpResumeCode'

const TwoFactorSetup = () => {
  const [totpData, setTotpData] = useState<GetTotpKeyData | null>(null)
  const [loading, setLoading] = useState(true)
  const [selectedAuthenticator, setSelectedAuthenticator] = useState(1)
  const [showBackupKeyUpdatedAlert, setShowBackupKeyUpdatedAlert] =
    useState(false)
  const navigate = useNavigate()
  const merchantMemberProfile = useMerchantMemberProfileStore()

  useEffect(() => {
    const profile = merchantMemberProfile.getProfile()
    if (profile.totpType && profile.totpType > 0) {
      message.info('You have already set up two-factor authentication')
      navigate('/')
      return
    }
    fetchTotpData()
  }, [navigate, merchantMemberProfile])

  useEffect(() => {
    if (totpData?.totpResumeCode) {
      const currentKey = totpData.totpResumeCode
      const previousKey = sessionStorage.getItem(
        SESSION_STORAGE_KEY_PREVIOUS_TOTP_RESUME_CODE
      )
      if (previousKey && previousKey !== currentKey) {
        setShowBackupKeyUpdatedAlert(true)
      }
      sessionStorage.setItem(
        SESSION_STORAGE_KEY_PREVIOUS_TOTP_RESUME_CODE,
        currentKey
      )
    }
  }, [totpData])

  const fetchTotpData = async () => {
    try {
      const [data, err] = await getTotpKeyReq(selectedAuthenticator)
      if (err) {
        message.error('Failed to get TOTP key')
        return
      }
      setTotpData(data)
    } catch {
      message.error('Failed to get TOTP key')
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = () => {
    if (totpData?.totpResumeCode) {
      navigator.clipboard.writeText(totpData.totpResumeCode)
      message.success('Backup key copied to clipboard')
    }
  }

  const handleNext = () => {
    if (totpData?.totpKey) {
      sessionStorage.setItem('totpKey', totpData.totpKey)
      sessionStorage.setItem('totpType', selectedAuthenticator.toString())
      navigate('/two-factorverify')
    }
  }

  const handleSkip = () => {
    message.info('You can set up 2FA later in My Account settings')
    navigate('/plan/list')
  }

  if (loading) {
    return (
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          minHeight: '100vh'
        }}
      >
        <Spin size="large" />
      </div>
    )
  }

  return (
    <div
      style={{
        width: '100%',
        maxWidth: '1352px',
        margin: '0 auto',
        padding: '0 16px'
      }}
    >
      {showBackupKeyUpdatedAlert && (
        <div style={{ margin: '16px 0' }}>
          <Alert
            message="The backup key has been updated. Please make sure to save the new backup key securely."
            type="warning"
            showIcon
            icon={<CheckCircleOutlined style={{ color: '#faad14' }} />}
            closable
            onClose={() => setShowBackupKeyUpdatedAlert(false)}
            style={{
              maxWidth: '686px',
              margin: '0 auto'
            }}
          />
        </div>
      )}

      <div style={{ marginBottom: '32px', marginTop: '60px' }}>
        <h1
          style={{
            fontWeight: 600,
            marginBottom: '16px',
            textAlign: 'center',
            fontSize: '28px'
          }}
        >
          Set Up Two-Factor Authentication (2FA)
          <Tooltip title="Two-factor authentication adds an extra layer of security to your account. When logging in, you'll need to enter a verification code generated by your authenticator app in addition to your password.">
            <InfoCircleOutlined
              style={{
                marginLeft: '8px',
                fontSize: '20px',
                verticalAlign: 'middle'
              }}
            />
          </Tooltip>
        </h1>
      </div>

      <div
        style={{
          padding: '24px',
          backgroundColor: 'white',
          borderRadius: '8px',
          marginTop: '20px',
          minHeight: '660px'
        }}
      >
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            gap: '48px',
            justifyContent: 'center',
            flexWrap: 'wrap'
          }}
        >
          <div style={{ flex: 1, maxWidth: '600px' }}>
            <h2
              style={{
                fontSize: '20px',
                fontWeight: 600,
                marginBottom: '24px',
                marginTop: '40px',
                marginLeft: '40px'
              }}
            >
              Setup Guide
            </h2>

            <div
              style={{
                display: 'flex',
                flexDirection: 'column',
                gap: '32px',
                marginLeft: '40px'
              }}
            >
              <div>
                <h3 style={{ fontSize: '18px', fontWeight: 500, marginBottom: '8px' }}>
                  1. Download and Install
                </h3>
                <p style={{ color: '#6B7280', marginBottom: '16px' }}>
                  Download the app from the App Store or Google Play Store
                </p>
              </div>

              <div>
                <h3 style={{ fontSize: '18px', fontWeight: 500, marginBottom: '8px' }}>
                  2. Open the App and Add New Account
                </h3>
                <p style={{ color: '#6B7280' }}>
                  In the app, tap the "+" or "Add" button to begin setup
                </p>
              </div>

              <div>
                <h3 style={{ fontSize: '18px', fontWeight: 500, marginBottom: '8px' }}>
                  3. Scan QR Code
                </h3>
                <p style={{ color: '#6B7280' }}>
                  Use the app to scan the QR code shown on the right
                </p>
              </div>

              <div>
                <h3 style={{ fontSize: '18px', fontWeight: 500, marginBottom: '8px' }}>
                  4. Save Backup Key
                </h3>
                <p style={{ color: '#6B7280' }}>
                  Store the backup key below safely in case you lose your device
                </p>
                <div
                  style={{
                    marginTop: '16px',
                    padding: '16px',
                    borderRadius: '8px',
                    border: '1px solid #E5E7EB',
                    background: '#F9FAFB',
                    maxWidth: '603px'
                  }}
                >
                  <div
                    style={{
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center'
                    }}
                  >
                    <span style={{ color: '#374151', fontWeight: 500 }}>
                      Backup Key
                    </span>
                    <Button
                      type="link"
                      icon={<CopyOutlined />}
                      onClick={handleCopy}
                      style={{ padding: 0 }}
                    >
                      Copy
                    </Button>
                  </div>
                  <div
                    style={{
                      marginTop: '12px',
                      padding: '12px',
                      backgroundColor: 'white',
                      borderRadius: '6px',
                      border: '1px solid #E5E7EB'
                    }}
                  >
                    <code
                      style={{
                        color: '#1F2937',
                        display: 'block',
                        width: '100%',
                        wordBreak: 'break-all'
                      }}
                    >
                      {totpData?.totpResumeCode}
                    </code>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            style={{
              flex: 1,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}
          >
            {totpData?.totpUrl && (
              <TwoFactorQRCode
                value={totpData.totpUrl}
                secretKey={totpData.totpKey || ''}
                accountName={merchantMemberProfile.getProfile().email}
                authenticatorOptions={authenticatorOptions}
                selectedAuthenticator={selectedAuthenticator}
                onAuthenticatorChange={(value) => {
                  setSelectedAuthenticator(value)
                }}
              />
            )}
          </div>
        </div>
      </div>

      <div
        style={{
          position: 'sticky',
          bottom: 0,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginTop: '32px',
          paddingBottom: '16px',
          borderTop: '1px solid #E5E7EB',
          paddingTop: '16px',
          backgroundColor: '#f5f5f5'
        }}
      >
        <Button size="large" onClick={handleSkip}>
          Skip
        </Button>
        <Button type="primary" size="large" onClick={handleNext}>
          Next
        </Button>
      </div>
    </div>
  )
}

export default TwoFactorSetup
