import type { InputRef } from 'antd'
import { Button, Form, Input, Modal, message, Alert } from 'antd'
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { emailValidate } from '../../helpers'
import { useAppInitialize } from '../../hooks/useAppInitialize'
import { clearTotpReq, loginWithPasswordReq } from '../../requests'
import { useMerchantMemberProfileStore, useSessionStore } from '../../stores'

// 2FA verification code component
const TwoFactorVerificationModal = ({
  visible,
  onCancel,
  onSubmit,
  loading,
  email,
  errorMessage
}: {
  visible: boolean
  onCancel: () => void
  onSubmit: (code: string) => void
  loading: boolean
  email: string
  errorMessage?: string
}) => {
  const [verificationCode, setVerificationCode] = useState([
    '',
    '',
    '',
    '',
    '',
    ''
  ])
  const [showCollapsed, setShowCollapsed] = useState(false)
  const [backupKey, setBackupKey] = useState('')
  const [isResetting, setIsResetting] = useState(false)
  const [showConfirmDialog, setShowConfirmDialog] = useState(false)
  const [resetSuccess, setResetSuccess] = useState(false)

  const handleInputChange = (index: number, value: string) => {
    if (value.length <= 1 && /^\d*$/.test(value)) {
      const newCode = [...verificationCode]
      newCode[index] = value
      setVerificationCode(newCode)

      if (value && index < 5) {
        const nextInput = document.getElementById(`2fa-code-${index + 1}`)
        nextInput?.focus()
      }
    }
  }

  const handlePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault()
    const pastedData = e.clipboardData
      .getData('text')
      .replace(/\D/g, '')
      .slice(0, 6)
    if (pastedData.length > 0) {
      const newCode = [...verificationCode]
      for (let i = 0; i < 6; i++) {
        newCode[i] = pastedData[i] || ''
      }
      setVerificationCode(newCode)
      const focusIndex = Math.min(pastedData.length, 5)
      const targetInput = document.getElementById(`2fa-code-${focusIndex}`)
      targetInput?.focus()
    }
  }

  const handleKeyDown = (
    index: number,
    e: React.KeyboardEvent<HTMLInputElement>
  ) => {
    if (e.key === 'Backspace' && !verificationCode[index] && index > 0) {
      const prevInput = document.getElementById(`2fa-code-${index - 1}`)
      prevInput?.focus()
    }
  }

  const handleVerify = () => {
    const code = verificationCode.join('')
    if (code.length !== 6) {
      message.error('Please enter a complete 6-digit code')
      return
    }
    onSubmit(code)
  }

  const handleResetTotp = async () => {
    if (!backupKey) {
      message.error('Please enter your backup key')
      return
    }
    setShowConfirmDialog(true)
  }

  const handleConfirmReset = async () => {
    setIsResetting(true)

    try {
      const [, err] = await clearTotpReq(email, backupKey)

      if (err) {
        message.error(
          err.message || 'Failed to reset 2FA. Please check your backup key.'
        )
        setIsResetting(false)
        return
      }

      setResetSuccess(true)
      setShowConfirmDialog(false)
      setTimeout(() => {
        onCancel()
      }, 3000)
    } catch {
      message.error('An unexpected error occurred. Please try again later.')
    } finally {
      setIsResetting(false)
    }
  }

  // Reset state when modal closes
  useEffect(() => {
    if (!visible) {
      setVerificationCode(['', '', '', '', '', ''])
      setShowCollapsed(false)
      setBackupKey('')
      setResetSuccess(false)
    }
  }, [visible])

  return (
    <>
      <Modal
        title="Two-Factor Authentication"
        open={visible}
        footer={null}
        onCancel={onCancel}
        centered
        width={400}
      >
        {resetSuccess && (
          <Alert
            message="Your 2FA has been reset successfully. You can now log in without 2FA."
            type="success"
            showIcon
            style={{ marginBottom: '16px' }}
          />
        )}

        <div style={{ padding: '16px 0' }}>
          <p
            style={{
              marginBottom: '24px',
              textAlign: 'center',
              color: '#6B7280'
            }}
          >
            Please enter the 6-digit verification code generated by your
            authenticator app to complete the login process.
          </p>

          {errorMessage && (
            <div
              style={{
                marginBottom: '16px',
                padding: '12px',
                backgroundColor: '#FEF2F2',
                border: '1px solid #FECACA',
                borderRadius: '8px'
              }}
            >
              <p
                style={{ color: '#DC2626', fontSize: '14px', textAlign: 'center' }}
              >
                {errorMessage}
              </p>
            </div>
          )}

          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              gap: '8px',
              marginBottom: '16px'
            }}
          >
            {verificationCode.map((digit, index) => (
              <Input
                key={index}
                id={`2fa-code-${index}`}
                maxLength={1}
                value={digit}
                onChange={(e) => handleInputChange(index, e.target.value)}
                onKeyDown={(e) =>
                  handleKeyDown(index, e as React.KeyboardEvent<HTMLInputElement>)
                }
                onPaste={handlePaste}
                disabled={loading}
                autoFocus={index === 0}
                style={{
                  width: '48px',
                  height: '48px',
                  textAlign: 'center',
                  fontSize: '18px'
                }}
              />
            ))}
          </div>

          <Button
            type="primary"
            onClick={handleVerify}
            loading={loading}
            disabled={loading || verificationCode.join('').length !== 6}
            style={{ width: '100%', marginBottom: '12px' }}
          >
            Verify
          </Button>

          <div style={{ marginTop: '16px' }}>
            <div
              style={{
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                color: '#6B7280'
              }}
              onClick={() => setShowCollapsed(!showCollapsed)}
            >
              <span
                style={{
                  marginRight: '4px',
                  transform: showCollapsed ? 'rotate(180deg)' : 'none',
                  transition: 'transform 0.2s'
                }}
              >
                ▼
              </span>
              Lost your 2FA?
            </div>

            {showCollapsed && (
              <div
                style={{
                  marginTop: '16px',
                  borderTop: '1px solid #F3F4F6',
                  paddingTop: '16px'
                }}
              >
                <div
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '24px'
                  }}
                >
                  <div
                    style={{
                      border: '1px solid #E5E7EB',
                      borderRadius: '8px',
                      padding: '16px'
                    }}
                  >
                    <h4
                      style={{
                        fontSize: '14px',
                        fontWeight: 500,
                        marginBottom: '8px'
                      }}
                    >
                      Option 1: Reset via Backup Key
                    </h4>
                    <p
                      style={{
                        fontSize: '12px',
                        color: '#6B7280',
                        marginBottom: '12px'
                      }}
                    >
                      Enter your backup key to reset your two-factor
                      authentication.
                    </p>

                    <Input
                      placeholder="Enter your backup key"
                      value={backupKey}
                      onChange={(e) => setBackupKey(e.target.value)}
                      style={{ marginBottom: '12px' }}
                    />
                    <Button
                      type="primary"
                      onClick={handleResetTotp}
                      loading={isResetting}
                      disabled={isResetting || !backupKey}
                      style={{ width: '100%' }}
                    >
                      Reset
                    </Button>
                  </div>

                  <div
                    style={{
                      border: '1px solid #E5E7EB',
                      borderRadius: '8px',
                      padding: '16px'
                    }}
                  >
                    <h4
                      style={{
                        fontSize: '14px',
                        fontWeight: 500,
                        marginBottom: '8px'
                      }}
                    >
                      Option 2: Contact Admin
                    </h4>
                    <p
                      style={{
                        fontSize: '12px',
                        color: '#6B7280',
                        marginBottom: '12px'
                      }}
                    >
                      If you've lost both 2FA and backup key, please contact your
                      system administrator to reset your 2FA.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </Modal>

      <Modal
        title="Confirm 2FA Reset"
        open={showConfirmDialog}
        onCancel={() => setShowConfirmDialog(false)}
        footer={[
          <Button key="cancel" onClick={() => setShowConfirmDialog(false)}>
            Cancel
          </Button>,
          <Button
            key="confirm"
            type="primary"
            loading={isResetting}
            onClick={handleConfirmReset}
            danger
          >
            Confirm Reset
          </Button>
        ]}
        centered
        width={500}
      >
        <p style={{ color: '#374151', marginBottom: '16px' }}>
          Warning: This action will disable your current two-factor
          authentication. You will need to set up 2FA again to secure your
          account. Are you sure you want to proceed?
        </p>
      </Modal>
    </>
  )
}

const Index = ({
  email,
  onEmailChange,
  triggeredByExpired,
  setLogging
}: {
  email: string
  onEmailChange: (value: string) => void
  triggeredByExpired: boolean
  setLogging: (val: boolean) => void
}) => {
  const appInitialize = useAppInitialize()
  const merchantMemberProfile = useMerchantMemberProfileStore()
  const sessionStore = useSessionStore()
  const [errMsg, setErrMsg] = useState('')
  const navigate = useNavigate()
  const [submitting, setSubmitting] = useState(false)
  const [form] = Form.useForm()
  const watchEmail = Form.useWatch('email', form)
  const passwordRef = useRef<InputRef>(null)
  const emailRef = useRef<InputRef>(null)

  // 2FA related states
  const [is2FAModalVisible, setIs2FAModalVisible] = useState(false)
  const [loginCredentials, setLoginCredentials] = useState<{
    email: string
    password: string
  } | null>(null)
  const [twoFAErrorMessage, setTwoFAErrorMessage] = useState('')

  const onForgetPass = async () => {
    try {
      await form.validateFields(['email'])
    } catch {
      message.error('Please enter a valid email address first')
      return
    }

    const email = form.getFieldValue('email')
    if (!email || !emailValidate(email)) {
      message.error('Please enter a valid email address first')
      return
    }

    const encodedEmail = encodeURIComponent(email)
    navigate(`/forgot-password?email=${encodedEmail}`)
  }

  const handle2FASubmit = async (twoFactorCode: string) => {
    if (!loginCredentials) return

    setSubmitting(true)
    setTwoFAErrorMessage('')

    const credentials = {
      ...loginCredentials,
      totpCode: twoFactorCode
    }

    const [loginRes, err] = await loginWithPasswordReq(credentials)

    if (err != null) {
      setSubmitting(false)
      setLogging(false)
      setTwoFAErrorMessage(err.message)
      return
    }

    const { merchantMember, token } = loginRes
    localStorage.setItem('merchantToken', token)
    merchantMember.token = token

    merchantMemberProfile.setProfile({
      ...merchantMember,
      totpType: merchantMember.totpType || 0
    })

    setIs2FAModalVisible(false)
    setTwoFAErrorMessage('')

    const defaultPage = await appInitialize()

    if (triggeredByExpired) {
      sessionStore.refreshCallbacks?.forEach((cb) => cb && cb())
      sessionStore.setSession({
        expired: false,
        refreshCallbacks: []
      })
      message.success('Login successful')
    } else {
      sessionStore.setSession({
        expired: false,
        refreshCallbacks: []
      })
      navigate(defaultPage)
    }
  }

  const onSubmit = async () => {
    setErrMsg('')
    setSubmitting(true)
    setLogging(true)

    const credentials = form.getFieldsValue()
    setLoginCredentials(credentials)

    const [loginRes, err] = await loginWithPasswordReq(credentials)

    if (err != null) {
      // Check if 2FA verification is needed (error code 49)
      if (
        err.message === '2FA Code Needed' ||
        (typeof err === 'object' && 'code' in err && err.code === 49)
      ) {
        setSubmitting(false)
        setIs2FAModalVisible(true)
        return
      }

      setSubmitting(false)
      setLogging(false)
      setErrMsg(err.message)
      return
    }

    const { merchantMember, token } = loginRes
    localStorage.setItem('merchantToken', token)
    merchantMember.token = token

    merchantMemberProfile.setProfile({
      ...merchantMember,
      totpType: merchantMember.totpType || 0
    })

    const defaultPage = await appInitialize()

    if (triggeredByExpired) {
      sessionStore.refreshCallbacks?.forEach((cb) => cb && cb())
      sessionStore.setSession({
        expired: false,
        refreshCallbacks: []
      })
      message.success('Login successful')
    } else {
      sessionStore.setSession({
        expired: false,
        refreshCallbacks: []
      })
      navigate(defaultPage)
    }
  }

  useEffect(() => {
    if (watchEmail != null) {
      onEmailChange(watchEmail)
    }
  }, [watchEmail])

  useEffect(() => {
    if (triggeredByExpired) {
      passwordRef.current?.focus()
    } else {
      emailRef.current?.focus()
    }
  }, [])

  return (
    <>
      <TwoFactorVerificationModal
        visible={is2FAModalVisible}
        onCancel={() => {
          setIs2FAModalVisible(false)
          setSubmitting(false)
          setLogging(false)
          setTwoFAErrorMessage('')
        }}
        onSubmit={handle2FASubmit}
        loading={submitting}
        email={form.getFieldValue('email')}
        errorMessage={twoFAErrorMessage}
      />

      <Form
        form={form}
        onFinish={onSubmit}
        disabled={submitting}
        name="login-password"
        labelCol={{ span: 6 }}
        wrapperCol={{ span: 18 }}
        style={{ maxWidth: 640, width: 360, position: 'relative' }}
        initialValues={{ email, password: '' }}
      >
        <Form.Item
          label="Email"
          name="email"
          rules={[
            {
              required: true,
              message: 'Please input your Email!'
            },
            () => ({
              validator(_, value) {
                if (value != null && value != '' && emailValidate(value)) {
                  return Promise.resolve()
                }
                return Promise.reject('Please input valid email address.')
              }
            })
          ]}
        >
          <Input onPressEnter={form.submit} ref={emailRef} />
        </Form.Item>

        <Form.Item
          label="Password"
          name="password"
          rules={[
            {
              required: true,
              message: 'Please input your password!'
            }
          ]}
        >
          <Input.Password onPressEnter={form.submit} ref={passwordRef} />
        </Form.Item>

        <div style={{ position: 'absolute', right: '-130px', top: '56px' }}>
          <Button
            onClick={onForgetPass}
            type="link"
            style={{ fontSize: '11px' }}
          >
            Forgot Password?
          </Button>
        </div>

        <div className="mb-4 flex justify-center text-red-500">{errMsg}</div>
        <div className="flex w-full justify-center">
          <Button
            type="primary"
            onClick={form.submit}
            loading={submitting}
            disabled={submitting}
          >
            Submit
          </Button>
        </div>
      </Form>
    </>
  )
}

export default Index
