name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string 
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3 

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Extract version
        id: extract_version
        run: |
          if [[ ${{ steps.branch-names.outputs.current_branch }} =~ ^[^/]+/(v[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "No version found"
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build dev image and push
        if: inputs.environment == 'development'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: unibee/unibee-merchant-portal:${{ steps.extract_version.outputs.version }}-dev

