name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build
        run: echo "Building the project" 

      - name: Deploy to ${{ inputs.environment }} environment
        run: echo "Deploy to the ${{ inputs.environment }} environment"

      

