# This script used to release an arbitrary version of the application.
# It dose not generate release notes, but it does push the image to Docker Hub.
name: Release an arbitrary version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-arb\.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build prod image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: unibee/admin-portal:${{ github.ref_name }}
